### ISSUE TITLE
GitHub repository maintenance

### ISSUE THREAD

**Issue by liledix4** [liledix4/BvS-Website#2]
Copy the following from the [original repository](https://github.com/BvSGame/bvsgame.github.io):

- Issues
    - [x] Milestones
    - [x] Labels

**Comment by liledix4** [comment]
## New labels

- [x] Browser games
- [x] CSS
- [x] From older website
- [x] Gulp
- [x] HTML
- [x] JavaScript
- [x] JSON
- [x] Local storage (browser)
- [x] Markdown
- [x] Node.js
- [x] PHP
- [x] Static files

**Comment by liledix4** [comment]
## Add labels
- [x] HTML Page (URL-Accessible)
## Fix labels
- [x] HTML Template
